server:
  port: 9999

#spring:
#  datasource:
#    username: root
#    initialization-mode: always
#    url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
#    platform: root
#    password: 0003pray
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        show_sql: true
#        format_sql: true
#    hibernate:
#      ddl-auto: update
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
#jwt:
#  secret: secret

